apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: uxgys494f-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/uxgys494f-java-quarkus-gitops